
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ise-app-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: "dev"
  GREETING: "Hallo ISE aus DEV üë®‚Äçüíª"
---
apiVersion: v1
kind: Secret
metadata:
  name: ise-app-secrets
  namespace: dev
type: Opaque
stringData:
  DB_PASSWORD: "dev-secret-change-me"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ise-app
  namespace: dev
  labels: { app: ise-app }
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  selector:
    matchLabels: { app: ise-app }
  template:
    metadata:
      labels: { app: ise-app }
    spec:
      containers:
        - name: ise-app
          image: ghcr.io/hamoosoft/ise-app/ise-app:latest
          imagePullPolicy: IfNotPresent
          ports: [ { containerPort: 9090 } ]
          envFrom:
            - configMapRef: { name: ise-app-config }
            - secretRef:    { name: ise-app-secrets }
          readinessProbe:
            httpGet: { path: /actuator/health, port: 9090 }
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet: { path: /actuator/health, port: 9090 }
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: ise-service
  namespace: dev
spec:
  selector: { app: ise-app }
  ports:
    - name: http
      port: 80
      targetPort: 9090
  type: ClusterIP